export default {
  menus: (state) => { return state.layout.menus },
  scrollBar: (state) => { return state.layout.scrollBar },
  qrImg: (state) => { return state.user.qrImg },
  qrState: (state) => { return state.user.qrState },
  userAccount: (state) => { return state.user.account },
  userProfile: (state) => { return state.user.profile },
  showLogin: (state) => { return state.user.showLogin },
  songListId: (state) => { return state.playlist.songListId },
  songlist: (state) => { return state.playlist.songlist },
  music: (state) => { return state.player.music },
  currentMusicIndex: (state) => { 
    return state.player.playerList.findIndex(
      song => song.id === state.player.musicId
    ); 
  },
  playerListId: (state) => { return state.player.playerListId },
  playerList: (state) => { return state.player.playerList },
  playerListLen: (state) => { return state.player.playerList.length },
  volume: (state) => { return state.player.volume },
  currentTime: (state) => { return state.player.currentTime },
  duration: (state) => { return state.player.duration },
  isPause: (state) => { return state.player.isPause },
  isMuted: (state) => { return state.player.isMuted },
  loopType: (state) => { return state.player.loopType },
  showPlayerList: (state) => { return state.player.showPlayerList },
  mvDetail: (state) => { return state.videodetail.mvDetail },
  mvUrl: (state) => { return state.videodetail.mvUrl },
  videoDetail: (state) => { return state.videodetail.videoDetail },
  videoUrl: (state) => { return state.videodetail.videoUrl },
  relatedAllVideo: (state) => { return state.videodetail.relatedAllVideo },
  selectArea: (state) => { return state.video.selectArea },
  selectKind: (state) => { return state.video.selectKind },
  selectOrder: (state) => { return state.video.selectOrder },
  areas: (state) => { return state.video.areas },
  kinds: (state) => { return state.video.kinds },
  orders: (state) => { return state.video.orders },
}